---
title: "Figures of clinical risk models"
output:
  html_document:
    theme: united
    highlight: tango
params:
    data: "/Users/rosal/OneDrive - University of Utah/2020/analyze/data/transcriptome-dimensions/analysis/20200802_pipe_out.rdata"
---

```{r load_packages, message=F, include=F}
# Install and load required R packages
library(dplyr)
library(data.table)
library(ggplot2)
#library(MASS)
#library(gridExtra)
```

Load model results
```{r}
setwd("C:/Users/rosal/github/transcriptome-dimensions/notebook/")
load(file = "rdata/mod.demographic-risk.rdata") # generated in demographic-risk.Rmd
#load(file = params$data) # load processed data
```

Setup
```{r}
theme_set(theme_minimal() + 
            theme(legend.position="none",
                  axis.title=element_text(size=8),
                  axis.text=element_text(size=7)))
```

### 1. Age
```{r}
#dt = merge(clinical[,c("SEQ_ID","D_PT_age")],score_sd) # Select data
#fit = lm.age
#fit.coeff = summary(fit)$coeff[-1,] %>% data.table()
#fit.coeff$PC = colnames(dt[,-c("SEQ_ID","score")])
#dt[,psl:= rowSums(data.matrix(dt %>% dplyr::select(contains("PC"))) %*% diag(fit.coeff$Estimate)) + summary(fit)$coeff[1,1]]
#pdt = data.frame(age = md$model$D_PT_age,predictors = md$fitted.values,psl = dt$psl)

md = lm.age
pdt = data.frame(age = md$model$D_PT_age,predictors = md$fitted.values)

p1 = ggplot(pdt,aes(y = predictors, x = age)) +
  geom_point(color = "#FF000060") +
  #geom_point(data=pdt[SEQ_ID=="MMRF_2778_1_BM",],aes(y = combined, x = score),
  #           shape = 21, color = "black", fill = "#FF0000", size = 2, stroke = 2) +
  theme_classic()+
  xlab("Dx Age") + ylab("PSL Score") +
  theme(legend.position="none",
        axis.title=element_text(size=8))
p1
#ggsave(filename = "plots/age_dot.pdf",plot = p1,width=3.5,height=3.5)
```
### 2. Gender
```{r}
md = glm.gender
pdt = data.frame(gender = md$model$D_PT_gender,predictors = md$linear.predictors)

p2 = ggplot(pdt, aes(x = factor(gender), y = predictors, fill = gender)) +
  scale_fill_manual(values = c('#E69F00', '#56B4E9')) +
  geom_violin() +
  #ylim(c(-15,6)) +
  #theme(axis.text.y=element_blank())+
  scale_x_discrete(labels=c("1" = "male", "2" = "female")) +
  ylab("PSL score") + xlab("gender")
p2
#ggsave(filename = "plots/t1416_violin.pdf",plot = p2,width=1.25,height=2.5)
```
### 3. Race
```{r}
md = glm.race
pdt = data.frame(race = md$model$D_PT_race,predictors = md$linear.predictors)

p3 = ggplot(pdt, aes(x = factor(race), y = predictors, fill = race)) +
  scale_fill_manual(values = c('#E69F00', '#56B4E9')) +
  geom_violin() +
  #ylim(c(-15,6)) +
  #theme(axis.text.y=element_blank())+
  scale_x_discrete(labels=c("1" = "white", "2" = "black")) +
  ylab("PSL score") + xlab("self identified race")
p3
#ggsave(filename = "plots/t1416_violin.pdf",plot = p2,width=1.25,height=2.5)
```

### 4. Ethnicity
```{r}
md = glm.ethnic
pdt = data.frame(ethnic = md$model$D_PT_ethnic,predictors = md$linear.predictors)

p4 = ggplot(pdt, aes(x = factor(ethnic), y = predictors, fill = ethnic)) +
  scale_fill_manual(values = c('#E69F00', '#56B4E9')) +
  geom_violin() +
  #ylim(c(-15,6)) +
  #theme(axis.text.y=element_blank())+
  scale_x_discrete(labels=c("1" = "non-Hispanic", "2" = "Hispanic")) +
  ylab("PSL score") + xlab("self identified ethnicity")
p4
#ggsave(filename = "plots/t1416_violin.pdf",plot = p2,width=1.25,height=2.5)
```

