---
title: "Overivew figure of spectra and model results"
output:
  html_document:
    theme: united
    highlight: tango
---

```{r load_packages, message=F, include=F}
# Install and load required R packages
library(dplyr)
library(data.table)
library(ggplot2)
library(MASS)
library("survival")
library("survminer")
library(lmtest)
```

Load model results
```{r}
setwd("C:/Users/rosal/github/transcriptome-dimensions/notebook/")
load(file = "rdata/lm.expression-scores.rdata") # generated in expression-scores.Rmd
load(file = "rdata/mod.clinical-risk.rdata") # generated in clinical-risk.Rmd
load(file = "rdata/mod.demographic-risk.rdata") # generated in demographic-risk.Rmd
load(file = "rdata/mod.disease-course.rdata") # generated in disease-course.Rmd
```

### Expression scores

**UAMS-70**
```{r}
md = lm.70
md.dt = data.table(actual=md$model$score,predicted=md$fitted.values)
summary(lm(data = md.dt,formula = actual ~ predicted))
```

**SBUK-17**
```{r}
md = lm.17
md.dt = data.table(actual=md$model$score,predicted=md$fitted.values)
summary(lm(data = md.dt,formula = actual ~ predicted))
```

### Clinical risk

**del(17p)**
```{r}
md = mod.risk$d17p
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_TRI_CF_ABNORMALITYPR11 ~ predicted,family = "binomial"))
```

**t(14;16)**
```{r}
md = mod.risk$t1416
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_TRI_CF_ABNORMALITYPR8 ~ predicted,family = "binomial"))
```

**amp(1q)**
```{r}
md = mod.risk$a1q
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_TRI_CF_ABNORMALITYPR13 ~ predicted,family = "binomial"))
```

**t(4;14)**
```{r}
md = mod.risk$t414
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_TRI_CF_ABNORMALITYPR3 ~ predicted,family = "binomial"))
```

**t(11;14)**
```{r}
md = mod.risk$t1114
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_TRI_CF_ABNORMALITYPR6 ~ predicted,family = "binomial"))
```

**ISS**
```{r}
md = mod.risk$iss
md.dt = data.frame(iss = md$model$ISS,predictors = md$lp)
summary(polr(data = md.dt, formula = iss ~ predictors, Hess = T))
```

### Disease course

**Overall Survival**
```{r}
md = os$coxph
md.dt = data.frame(time = md$y,predictors = md$linear.predictors)
coxph(data = md.dt, formula = time ~ predictors)
```

**Time to first line treatment failure (TTF)**
```{r}
md = tf1$coxph
md.dt = data.frame(time = md$y,predictors = md$linear.predictors)
coxph(data = md.dt, formula = time ~ predictors)
```

### Demographic risk

**Age**
```{r}
md = lm.age
md.dt = data.table(actual=md$model$D_PT_age,predicted=md$fitted.values)
summary(lm(data = md.dt,formula = actual ~ predicted))
```

**Gender**
```{r}
md = glm.gender
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_PT_gender ~ predicted,family = "binomial"))
```

**Race**
```{r}
md = glm.race
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_PT_race ~ predicted,family = "binomial"))
```

**Ethnicity**
```{r}
md = glm.ethnic
md.dt = data.table(md$data[,1],predicted=md$fitted.values)
summary(glm(data = md.dt,formula = D_PT_ethnic ~ predicted,family = "binomial"))
```
