---
title: "Figures of clinical risk models"
output:
  html_document:
    theme: united
    highlight: tango
---

!!! Define data directory !!!
```{r}
data_dir = "/path/to/data" # exclude ending "/"
```
```{r, include=FALSE}
# real data directory
data_dir = "/Users/rosal/OneDrive - University of Utah/2020/analyze/data/spectra.v2/data"
```

Load packages
```{r load_packages, message=F, include=T,error=F,warning=F}
# Install and load required R packages
library(dplyr)
library(data.table)
library(ggplot2)
library(ggpubr)
```

Load model results
```{r}
load(file = "rdata/mod.demographic-risk.rdata") # generated in demographic-risk.Rmd
load(file = "rdata/mod.clinical-risk.rdata") # generated in clinical-risk.Rmd

# read in spectra and clinical data
spectra_clinical = read.csv(file = paste0(data_dir,
                                  "/baseline-clinical-spectra-sd.csv")
                            ) %>% data.table()
```

Plot Setup
```{r}
theme_set(theme_classic() + 
            theme(legend.position="none",legend.key.size = unit(0.5,"line"),
                  legend.title = element_text(size=8),
                  legend.text = element_text(size=7),
                  axis.title=element_text(size=9),
                  axis.text=element_text(size=8)))
```


### a) amp(1q)
```{r}
# check poly-spectra liability score calculation
fit = mod.risk$a1q
dat = spectra_clinical %>% 
  dplyr::select("D_TRI_CF_ABNORMALITYPR13",starts_with("PC")) %>%
  dplyr::filter(D_TRI_CF_ABNORMALITYPR13!="Not Done" &
                D_TRI_CF_ABNORMALITYPR13!="") %>% data.table()

## calculate manually from beta values
est = summary(fit)$coeff[-1,1] %>% data.table
dat[,psl:= rowSums(data.matrix(dat[,-c("D_TRI_CF_ABNORMALITYPR13")]) %*%
                     diag(est$.)) + summary(fit)$coeff[1,1]]

pdt = dat[,c("D_TRI_CF_ABNORMALITYPR13","psl")]
```

Plot
```{r}
pdt = data.frame(a1q = fit$model$D_TRI_CF_ABNORMALITYPR13,
                 predictors = fit$linear.predictors)

setorder(pdt,-predictors)
w = ggplot(pdt,aes(y=predictors,x=1:nrow(pdt),fill=a1q)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values = c("gray","#F67280"), 
                    name = "amp(1q)", 
                    labels = c("N (n=323)","Y (n=202)")) +
  xlab("Patients (N=525)") + ylab("amp(1q) PSL Score") +
  scale_x_continuous(limits = c(0,nrow(pdt)+1), breaks=seq(1,nrow(pdt),1)) +
  theme(legend.position = c(1,1), legend.justification = c(1,1),
        axis.text = element_blank(), axis.ticks = element_blank())
w
ggsave(filename = "plots/a1q_waterfall.pdf",plot = w,width=3.75,height=2)
```


### b) t(11;14)
```{r}
# check poly-spectra liability score calculation
fit = mod.risk$t1114
dat = spectra_clinical %>% 
  dplyr::select("D_TRI_CF_ABNORMALITYPR6",starts_with("PC")) %>%
  dplyr::filter(D_TRI_CF_ABNORMALITYPR6!="Not Done" &
                D_TRI_CF_ABNORMALITYPR6!="") %>% data.table()

## calculate manually from beta values
est = summary(fit)$coeff[-1,1] %>% data.table
dat[,psl:= rowSums(data.matrix(dat[,-c("D_TRI_CF_ABNORMALITYPR6")]) %*%
                     diag(est$.)) + summary(fit)$coeff[1,1]]

pdt = dat[,c("D_TRI_CF_ABNORMALITYPR6","psl")]
```

Plot
```{r}
pdt = data.frame(t1114 = fit$model$D_TRI_CF_ABNORMALITYPR6,
                 predictors = fit$linear.predictors)

#nrow(pdt[pdt$t1114=="No",])
setorder(pdt,-predictors)
w = ggplot(pdt,aes(y=predictors,x=1:nrow(pdt),fill=t1114)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values = c("gray","#355C7D"), 
                    name = "t(11;14)", 
                    labels = c("N (n=441)","Y (n=153)")) +
  xlab("Patients (N=594)") + ylab("t(11;14) PSL Score") +
  scale_x_continuous(limits = c(0,nrow(pdt)+1), breaks=seq(1,nrow(pdt),1)) +
  #theme(legend.position = "top",
  theme(legend.position = c(1,1), legend.justification = c(1,1),
        axis.text = element_blank(), axis.ticks = element_blank())
w
ggsave(filename = "plots/t1114_waterfall.pdf",plot = w,width=3.75,height=2)
```


### c) ISS
```{r}
fit = mod.risk$iss
pdt = data.frame(iss = fit$model$ISS,predictors = fit$lp)

dat = spectra_clinical %>% 
  dplyr::select("D_PT_iss",starts_with("PC")) %>% data.table()

## calculate manually from beta values
#dat[,psl:= rowSums(data.matrix(dat[,-c("D_PT_iss")]) %*% diag(coef(fit)))]

## check on matching
#unique(round(sort(fit$lp),digits = 7) == round(sort(dat$psl),digits = 7))
```

Plot
```{r}
my_comparisons <- list( c("1", "2"), c("2", "3"), c("1", "3") )
b = ggboxplot(pdt, x = "iss", y = "predictors",
          color = "iss", add = "jitter",
          legend = "none", ylab = "ISS PSL Score", xlab = "ISS", 
          size = 1) + 
  stat_compare_means(comparisons = my_comparisons, size = 3) +
  theme_classic() + 
            theme(legend.position="none",legend.key.size = unit(0.5,"line"),
                  legend.title = element_text(size=8),
                  legend.text = element_text(size=7),
                  axis.title=element_text(size=9),
                  axis.text=element_text(size=8))

b
ggsave(filename = "plots/iss_boxplot.pdf",plot = b,width=3.75,height=4)
```


### d) gender x race
```{r}
## calculate PSL scores from beta values
dat = spectra_clinical %>% 
  dplyr::select("D_PT_gender","D_PT_race",starts_with("PC")) %>% data.table()
est = summary(glm.gender)$coeff[-1,1]
dat[,gender_psl:= rowSums(data.matrix(dat[,-c("D_PT_gender","D_PT_race")]) %*% diag(est)) + summary(glm.gender)$coeff[1,1]]

est = summary(glm.race)$coeff[-1,1]
dat[,race_psl:= rowSums(data.matrix(dat[,-c("D_PT_gender","D_PT_race","gender_psl")]) %*% diag(est)) + summary(glm.race)$coeff[1,1]]

pdt = dat[,c("D_PT_gender","D_PT_race","gender_psl","race_psl")]

# clean up data table
colnames(pdt) = c("gender","race","gender_psl","race_psl")

pdt$gender = as.factor(pdt$gender)
pdt[gender == 1,"gender"] = "male"
pdt[gender == 2,"gender"] = "female"

pdt$race = as.factor(pdt$race)
pdt[race == 1,"race"] = "white"
pdt[race == 2,"race"] = "black"

pdt$grp = ""
pdt[gender == "male" & race == "black","grp"] = "black_male"
pdt[gender == "male" & race == "white","grp"] = "white_male"
pdt[gender == "female" & race == "black","grp"] = "black_female"
pdt[gender == "female" & race == "white","grp"] = "white_female"

pdt$grp = as.factor(pdt$grp)
pdt
```

Plot
```{r}
my_comparisons = list(c("female","male"))

p2 = ggboxplot(pdt, x = "gender", y = "gender_psl",
          color = "gender", add = "jitter", palette = "jco",
          legend = "none", ylab = "Gender PSL Score", xlab = "", 
          size = 1, order = c("female","male")) +
    stat_compare_means(comparisons = my_comparisons, size = 3) +
    theme_classic() + 
            theme(legend.position="none",legend.key.size = unit(0.5,"line"),
                  legend.title = element_text(size=8),
                  legend.text = element_text(size=7),
                  axis.title=element_text(size=9),
                  axis.text=element_text(size=8))
p2
nrow(pdt[pdt$gender=="female"])
nrow(pdt[pdt$gender=="male"])
ggsave(filename = "plots/gender_boxplot.pdf",plot = p2,width=3.75,height=4)
```
```{r}
my_comparisons = list(c("black","white"))

p3 = ggboxplot(pdt[pdt$race%in%c("black","white")], x = "race", y = "race_psl",
          color = "race", add = "jitter", palette = "npg",
          legend = "none", ylab = "Race PSL Score", xlab = "", 
          size = 1, order = c("black","white")) +
    stat_compare_means(comparisons = my_comparisons, size = 3) +
    theme_classic() + 
            theme(legend.position="none",legend.key.size = unit(0.5,"line"),
                  legend.title = element_text(size=8),
                  legend.text = element_text(size=7),
                  axis.title=element_text(size=9),
                  axis.text=element_text(size=8))
p3
nrow(pdt[pdt$race=="black"])
nrow(pdt[pdt$race=="white"])
ggsave(filename = "plots/race_boxplot.pdf",plot = p3,width=3.75,height=4)
```
