---
title: "Figures of clinical risk models"
output:
  html_document:
    theme: united
    highlight: tango
---

```{r load_packages, message=F}
# Install and load required R packages
library("dplyr")
library("data.table")
library("ggplot2")
library("survminer")
library("survival")
```

Load model results
```{r}
load(file = "rdata/mod.disease-course.rdata")
```

Plotting setup
```{r}
cbPalette <- c("#999999","#E69F00","#56B4E9","#009E73","#F0E442","#0072B2",
               "#D55E00","#CC79A7")
```

Overall Survival (OS)
```{r}
md = os
pdt = data.frame(tme = md$data$ttcos, evt = md$data$censos,
                 predictors = md$coxph$linear.predictors)
pdt$trt = cut(pdt$predictors,quantile(pdt$predictors,c(0,1/3,2/3,1)),
              include.lowest = T,labels = F) #tertiles
pdt$yrs = pdt$tme/365

fit = survfit(Surv(time = pdt$yrs, event = pdt$evt) ~ trt, data=pdt)
temp.surv = summary(fit,times=c(1,3,5))
data.table(time=temp.surv$time,strata=temp.surv$strata,survival=temp.surv$surv)

p1 = ggsurvplot(survfit(Surv(time = pdt$yrs, event = pdt$evt) ~ trt, data=pdt),
           palette=cbPalette[c(6,1,7)],
           pval=F,pval.method = F,
           #risk.table = "percentage",tables.col = "strata",fontsize = 3,
           tables.y.text=FALSE,
           conf.int = TRUE,
           break.x.by = 1, xlab = "years",
           ggtheme = theme_set(theme_classic() + 
                                 theme(axis.title=element_text(size=11),
                                       axis.text=element_text(size=9),
                                       panel.grid.major.x = element_line(
                                         colour = "gray",linetype = 3))
                               )
           )
p1
#ggsave(plot = print(p1),filename = "plots/os-km.pdf",
 #      units = "in",width = 7.5,height = 4.5)
#survfit(Surv(time = pdt$tme, event = pdt$evt) ~ trt, data=pdt)

#summary(survfit(Surv(time = pdt$tme, event = pdt$evt) ~ trt, data=pdt))

survdiff(formula = Surv(time = pdt$tme, event = pdt$evt) ~ trt, data=pdt)
pchisq(120, df=2, lower.tail=FALSE)
```

Time to first line treatment failure (TTF)
```{r}
md = tf
pdt = data.frame(tme = md$data$ttctf1, evt = md$data$censtf1,
                 predictors = md$coxph$linear.predictors)
pdt$trt = cut(pdt$predictors,quantile(pdt$predictors,c(0,1/3,2/3,1)),
              include.lowest = T,labels = F) #tertiles
pdt$yrs = pdt$tme/365

#ttf = survfit(Surv(time = pdt$tme, event = pdt$evt) ~ trt, data=pdt)
#ttf
#summary(ttf)

fit = survfit(Surv(time = pdt$yrs, event = pdt$evt) ~ trt, data=pdt)
temp.surv = summary(fit,times=c(1,3,5))
data.table(time=temp.surv$time,strata=temp.surv$strata,survival=temp.surv$surv)

p2 = ggsurvplot(survfit(Surv(time = pdt$yrs, event = pdt$evt) ~ trt, data=pdt),
           palette=cbPalette[c(6,1,7)],
           conf.int = TRUE,
           break.x.by = 1, xlab = "years",
           ggtheme = theme_set(theme_classic() + 
                                 theme(axis.title=element_text(size=11),
                                       axis.text=element_text(size=9),
                                       panel.grid.major.x = element_line(
                                         colour = "gray",linetype = 3)
                                 )
                               )
           )
p2

#ggsave(plot = print(p2),filename = "plots/ttf-km.pdf",
 #      units = "in",width = 7.5,height = 4.5)

survdiff(formula = Surv(time = pdt$tme, event = pdt$evt) ~ trt, data=pdt)
pchisq(95.7, df=2, lower.tail=FALSE)
```