---
title: "Odds ratios for poly-spectra liability"
output:
  html_document:
    theme: united
    highlight: tango
---

```{r load_packages, message=F}
# Install and load required R packages
library("data.table")
library("dplyr")
library("knitr")
library("ggplot2")
```

Load model results
```{r}
load(file = "rdata/mod.clinical-risk.rdata") # generated in clinical-risk.Rmd
load(file = "rdata/mod.demographic-risk.rdata") # generated in demographic-risk.Rmd
load(file = "rdata/mod.disease-course.rdata") # generated in disease-course.Rmd
```

## del(17p)
```{r}
fit = mod.risk$d17p
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_TRI_CF_ABNORMALITYPR11,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/10,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="No") %>% group_by(decile) %>% count(category,name = "n_no")
tmp2 = dat %>% filter(category=="Yes") %>% group_by(decile) %>% count(category,name = "n_yes")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% dplyr::select("decile","n_no","n_yes"))
kable(cnt,align = 'c',caption = "del(17p) PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_yes]
b = cnt[decile%in%c(10),n_no]
c = sum(cnt[decile%in%c(5,6),n_yes])
d = sum(cnt[decile%in%c(5,6),n_no])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: del(17p) PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## t(14;16)
```{r, results = 'asis'}
fit = mod.risk$t1416
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_TRI_CF_ABNORMALITYPR8,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/5,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="No") %>% group_by(decile) %>% count(category,name = "n_no")
tmp2 = dat %>% filter(category=="Yes") %>% group_by(decile) %>% count(category,name = "n_yes")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% dplyr::select("decile","n_no","n_yes"))
kable(cnt,align = 'c',caption = "t(14;16) PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_yes]
b = cnt[decile%in%c(10),n_no]
c = sum(cnt[decile%in%c(5,6),n_yes])
d = sum(cnt[decile%in%c(5,6),n_no])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: t(14;16) PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## amp(1q)
```{r}
fit = mod.risk$a1q
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_TRI_CF_ABNORMALITYPR13,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/5,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="No") %>% group_by(decile) %>% count(category,name = "n_no")
tmp2 = dat %>% filter(category=="Yes") %>% group_by(decile) %>% count(category,name = "n_yes")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% dplyr::select("decile","n_no","n_yes"))
kable(cnt,align = 'c',caption = "amp(1q) PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_yes]
b = cnt[decile%in%c(10),n_no]
c = sum(cnt[decile%in%c(5,6),n_yes])
d = sum(cnt[decile%in%c(5,6),n_no])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: amp(1q) PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## t(4;14)
```{r}
fit = mod.risk$t414
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_TRI_CF_ABNORMALITYPR3,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/5,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="No") %>% group_by(decile) %>% count(category,name = "n_no")
tmp2 = dat %>% filter(category=="Yes") %>% group_by(decile) %>% count(category,name = "n_yes")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% dplyr::select("decile","n_no","n_yes"))
kable(cnt,align = 'c',caption = "t(4;14) PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_yes]
b = cnt[decile%in%c(10),n_no]
c = sum(cnt[decile%in%c(5,6),n_yes])
d = sum(cnt[decile%in%c(5,6),n_no])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: t(4;14) PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## t(11;14)
```{r}
fit = mod.risk$t1114
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_TRI_CF_ABNORMALITYPR6,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/5,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="No") %>% group_by(decile) %>% count(category,name = "n_no")
tmp2 = dat %>% filter(category=="Yes") %>% group_by(decile) %>% count(category,name = "n_yes")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% dplyr::select("decile","n_no","n_yes"))
kable(cnt,align = 'c',caption = "t(11;14) PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_yes]
b = cnt[decile%in%c(10),n_no]
c = sum(cnt[decile%in%c(5,6),n_yes])
d = sum(cnt[decile%in%c(5,6),n_no])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: t(11;14) PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## ISS
```{r}
fit = mod.risk$iss
psl = rowSums(data.matrix(fit$model[,-1]) %*% diag(coef(fit))) # multiple each PC by the PC beta, sum across PCs

# check PSL calculation
unique(round(fit$lp,12) == round(psl,12)) 
#data.table(psl,fit$lp)

# split into deciles
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$model$ISS,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/10,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category==1) %>% group_by(decile) %>% count(category,name = "n_1")
tmp2 = dat %>% filter(category==2) %>% group_by(decile) %>% count(category,name = "n_2")
tmp3 = dat %>% filter(category==3) %>% group_by(decile) %>% count(category,name = "n_3")
cnt = data.table(merge(merge(tmp1,tmp2,by=c("decile"),all = T),tmp3,by="decile",all=T))[,c("decile","n_1","n_2","n_3")]
kable(cnt,align = 'c',caption = "ISS PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_3]
b = cnt[decile%in%c(10),n_1]
c = sum(cnt[decile%in%c(5,6),n_3])
d = sum(cnt[decile%in%c(5,6),n_1])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: ISS PSL in decile 10 compared with deciles 5 + 6 for stage 1 v 3 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## Overall Survival (OS)
```{r}
# multiply each PC by the PC beta, sum across PCs
psl = rowSums(data.matrix(os$data[,-c(1:2)]) %*% diag(coef(os$coxph))) 

# check PSL calculation
unique(round(os$coxph$linear.predictors,12) == round(psl,12)) 
```

##### By tertile
```{r}
# split into tertiles
trl = cut(psl,quantile(psl,c(0,1/3,2/3,1)),
          include.lowest = T,labels = F)
dat = data.table(os$data[,c(1:2)],psl=psl,tertile=trl)
```

**OS at X years**
```{r}
dat$category = if_else(dat$ttcos<=324 & dat$censos==1,"dead",
                       if_else(dat$ttcos>324,"alive","censored")) 
```

Summarize counts by tertile at X years
```{r}
# number of events
evts = dat %>% filter(censos==1) %>% group_by(tertile) %>% 
  count(censos,name="events")  

# count number in each category
dead = dat %>% filter(category=="dead") %>% group_by(tertile) %>% 
  count(category,name = "n.dead")
aliv = dat %>% filter(category=="alive") %>% group_by(tertile) %>% 
  count(category,name = "n.alive")
cens = dat %>% filter(category=="censored") %>% group_by(tertile) %>% 
  count(category,name="n.censored")
cnt = data.table(
  merge(evts,
        merge(dead,
              merge(aliv,cens,by="tertile",all = T)
              ,by="tertile",all=T)
        ,by="tertile",all=T)
)[,c("tertile","events","n.dead","n.alive","n.censored")]
cnt
```

calculate hazard ratio
```{r}
a = cnt[tertile%in%c(3),n.dead]
b = cnt[tertile%in%c(3),n.alive]
c = sum(cnt[tertile%in%c(1),n.dead])
d = sum(cnt[tertile%in%c(1),n.alive])

hr = (a/b)/(c/d)
se = sqrt((1/a)+(1/b)+(1/c)+(1/d))
cil = exp(log(hr)-1.96*se)
ciu = exp(log(hr)+1.96*se)

paste0(round(hr,digits = 2)," (",
       round(cil,digits = 2),"-",
       round(ciu,digits = 2),")")

```



## Time to first line treatment failure (TTF)
```{r}
tf_psl = rowSums(data.matrix(tf$data[,-c(1:2)]) %*% diag(coef(tf$coxph))) # multiple each PC by the PC beta, sum across PCs

# check PSL calculation
unique(round(tf$coxph$linear.predictors,12) == round(tf_psl,12)) 
#data.table(tf1_psl,tf1$coxph$linear.predictors)

# split into decile
dcl = cut(tf_psl,quantile(tf_psl,c(0,1/3,2/3,1)),include.lowest = T,labels = F)
dat = data.table(tf$data[,c(1:2)],psl=tf_psl,decile=dcl)
```

**TTF at 1 year**
```{r}
dat$category = if_else(dat$ttctf1<=365 & dat$censtf1==1,"fail",if_else(dat$ttctf1>365,"okay","censored")) 
# describe if treatment has failed, not failed, or patient data censored
dat

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/10,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="fail") %>% group_by(decile) %>% count(category,name = "n_fail")
tmp2 = dat %>% filter(category=="okay") %>% group_by(decile) %>% count(category,name = "n_okay")
tmp3 = dat %>% filter(category=="censored") %>% group_by(decile) %>% count(category,name="n_censored")
cnt = data.table(merge(merge(tmp1,tmp2,by=c("decile"),all = T),tmp3,by="decile",all=T))[,c("decile","n_fail","n_okay","n_censored")]

# average days to death per decile - ignore censored values
avg_all = dat %>% filter() %>% group_by(decile) %>% summarise_at(vars(ttctf1),mean) 
avg_c1 = dat %>% filter(censtf1==1) %>% group_by(decile) %>% summarise_at(vars(ttctf1),mean)
avg_c0 = dat %>% filter(censtf1==0) %>% group_by(decile) %>% summarise_at(vars(ttctf1),mean)

# number of events per decile
evts = dat %>% filter(censtf1==1) %>% group_by(decile) %>% count(censtf1,name="n_events")  
c2 = data.table(merge(merge(avg_all,avg_c0,by = "decile"),merge(avg_c1,evts,by="decile")))[,-"censtf1"]
colnames(c2) = c("decile","avg_days","avg_days_censored","avg_days_fail","events")

merge(cnt,c2,by="decile")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_fail]
b = cnt[decile%in%c(10),n_okay]
c = sum(cnt[decile%in%c(5,6),n_fail])
d = sum(cnt[decile%in%c(5,6),n_okay])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("HR TTF PSL decile 10 compared with deciles 5 + 6 at 365 days = ",
       round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

**TTF at 3 years**
```{r}
dat$category = if_else(dat$ttctf1<=365*3 & dat$censtf1==1,"fail",if_else(dat$ttctf1>365*3,"okay","censored")) 
# describe if treatment has failed, not failed, or patient data censored
dat

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/10,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="fail") %>% group_by(decile) %>% count(category,name = "n_fail")
tmp2 = dat %>% filter(category=="okay") %>% group_by(decile) %>% count(category,name = "n_okay")
tmp3 = dat %>% filter(category=="censored") %>% group_by(decile) %>% count(category,name="n_censored")
cnt = data.table(merge(merge(tmp1,tmp2,by=c("decile"),all = T),tmp3,by="decile",all=T))[,c("decile","n_fail","n_okay","n_censored")]

# average days to death per decile - ignore censored values
avg_all = dat %>% filter() %>% group_by(decile) %>% summarise_at(vars(ttctf1),mean) 
avg_c1 = dat %>% filter(censtf1==1) %>% group_by(decile) %>% summarise_at(vars(ttctf1),mean)
avg_c0 = dat %>% filter(censtf1==0) %>% group_by(decile) %>% summarise_at(vars(ttctf1),mean)

# number of events per decile
evts = dat %>% filter(censtf1==1) %>% group_by(decile) %>% count(censtf1,name="n_events")  
c2 = data.table(merge(merge(avg_all,avg_c0,by = "decile"),merge(avg_c1,evts,by="decile")))[,-"censtf1"]
colnames(c2) = c("decile","avg_days","avg_days_censored","avg_days_fail","events")

# remove censored before X days
kable(merge(cnt,c2,by="decile"),align = 'c',
      caption = "Time to first treatment fail PSL decile counts at 3 years") 

# calculate hazards ratios
a = cnt[decile%in%c(10),n_fail]
b = cnt[decile%in%c(10),n_okay]
c = sum(cnt[decile%in%c(5,6),n_fail])
d = sum(cnt[decile%in%c(5,6),n_okay])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("HR TTF PSL decile 10 compared with deciles 5 + 6 at ",365*3,
       " days = ",round(hr10,digits = 2)," (",
       round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## Age
```{r}
fit = lm.age
psl = rowSums(data.matrix(fit$model[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,10) == round(psl,10)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(age=fit$model$D_PT_age,psl=psl,decile=dcl)
dat$category = as.factor(if_else(dat$age<60,1,2)) # two categories: <60 or >=60 at diagnosis

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/2,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="1") %>% group_by(decile) %>% count(category,name = "n_lt60")
tmp2 = dat %>% filter(category=="2") %>% group_by(decile) %>% count(category,name = "n_ge60")
avg = dat %>% filter() %>% group_by(decile) %>% summarise_at(vars(age),mean) # average days to death per decile - ignore censored values
cnt = data.table(merge(merge(tmp1,tmp2,by=c("decile"),all = T),avg,by="decile"))[,c("decile","n_lt60","n_ge60","age")]
kable(cnt,align = 'c',caption = "Age PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(1),n_lt60]
b = cnt[decile%in%c(1),n_ge60]
c = sum(cnt[decile%in%c(5,6),n_lt60])
d = sum(cnt[decile%in%c(5,6),n_ge60])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: Age PSL in decile 1 compared with deciles 5 + 6 for <60 or >=60 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## Gender
```{r}
fit = glm.gender
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_PT_gender,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/10,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="1") %>% group_by(decile) %>% count(category,name = "n_1")
tmp2 = dat %>% filter(category=="2") %>% group_by(decile) %>% count(category,name = "n_2")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% select("decile","n_1","n_2"))
kable(cnt,align = 'c',caption = "Gender PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_2]
b = cnt[decile%in%c(10),n_1]
c = sum(cnt[decile%in%c(5,6),n_2])
d = sum(cnt[decile%in%c(5,6),n_1])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: Gender PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## Race
```{r}
fit = glm.race
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_PT_race,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/5,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="1") %>% group_by(decile) %>% count(category,name = "n_1")
tmp2 = dat %>% filter(category=="2") %>% group_by(decile) %>% count(category,name = "n_2")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% select("decile","n_1","n_2"))
kable(cnt,align = 'c',caption = "Race PSL decile counts")

# calculate hazards ratios
a = cnt[decile%in%c(10),n_2]
b = cnt[decile%in%c(10),n_1]
c = sum(cnt[decile%in%c(5,6),n_2])
d = sum(cnt[decile%in%c(5,6),n_1])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: Race PSL in decile 10 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```

## Ethnicity
```{r}
fit = glm.ethnic
psl = rowSums(data.matrix(fit$data[,-1]) %*% diag(coef(fit)[-1])) + coef(fit)[1] # multiple each PC by the PC beta, sum across PCs, add the intercept beta

# check PSL calculation
unique(round(fit$fitted.values,12) == round(exp(psl)/(1+exp(psl)),12)) 
#data.table(PSL=psl,fitted_values=fit$fitted.values,ePSL=exp(psl)/(1+exp(psl))) # view data table 

# split into decile
dcl = cut(psl,quantile(psl,c(0,1/10,2/10,3/10,4/10,5/10,6/10,7/10,8/10,9/10,1)),include.lowest = T,labels = F)
dat = data.table(category=fit$data$D_PT_ethnic,psl=psl,decile=dcl)

# plot distribution
ggplot(dat) + geom_dotplot(aes(x=psl,fill=category),binwidth = 1/5,color="white") + theme_classic()

# count number in each category by decile
tmp1 = dat %>% filter(category=="1") %>% group_by(decile) %>% count(category,name = "n_1")
tmp2 = dat %>% filter(category=="2") %>% group_by(decile) %>% count(category,name = "n_2")
cnt = data.table(merge(tmp1,tmp2,by=c("decile"),all = T) %>% select("decile","n_1","n_2"))
kable(cnt,align = 'c',caption = "Ethnicity PSL decile counts")

cnt[is.na(cnt)] <- 0 # replace NA with 0

# calculate hazards ratios
a = cnt[decile%in%c(1),n_1]
b = cnt[decile%in%c(1),n_2]
c = sum(cnt[decile%in%c(5,6),n_1])
d = sum(cnt[decile%in%c(5,6),n_2])

hr10 = (a/b)/(c/d)
se10 = sqrt((1/a)+(1/b)+(1/c)+(1/d))
ci10_l = exp(log(hr10)-1.96*se10)
ci10_u = exp(log(hr10)+1.96*se10)

paste0("Odds Ratio: Ethnicity PSL in decile 1 compared with deciles 5 + 6 = ",round(hr10,digits = 2)," (",round(ci10_l,digits = 2),"-",round(ci10_u,digits = 2),")")
```





