#!/bin/bash

# Choose clinical data to investigate correlations

## Download data from https://research.themmrf.org/
### CoMMpass_IA14_FlatFiles.tar.gz
### CoMMpass_IA14_FlatFile_Dictionaries.tar.gz

CLIN_DIR=/home/rose/data/transcriptome-dimensions/input/CoMMpass_IA14_FlatFiles
